//! Plugin loader for Rust op shared libraries (cdylib).
//!
//! Loads `.so`/`.dylib`/`.dll` files at runtime via `libloading` and calls
//! Rust op functions through a stable C ABI. Libraries are cached after first load.
//!
//! Supports auto-build: paths pointing to `.rs` files, crate directories, or
//! `Cargo.toml` files are auto-detected, built via `cargo build --release`,
//! and the resulting shared library is loaded.
//!
//! ## C ABI Convention
//!
//! Plugin libraries export symbols generated by `rush_ops_sdk::export_ops!`:
//! - `rush_op_<name>(input_ptr, input_len, output_ptr, output_len) -> i32`
//! - `rush_ops_free(ptr, len)` — frees output buffers

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::sync::OnceLock;

use libloading::{Library, Symbol};

#[cfg(target_os = "macos")]
const LIB_PREFIX: &str = "lib";
#[cfg(target_os = "macos")]
const LIB_EXT: &str = "dylib";

#[cfg(target_os = "linux")]
const LIB_PREFIX: &str = "lib";
#[cfg(target_os = "linux")]
const LIB_EXT: &str = "so";

#[cfg(target_os = "windows")]
const LIB_PREFIX: &str = "";
#[cfg(target_os = "windows")]
const LIB_EXT: &str = "dll";

/// C ABI function signature for op execution.
///
/// Args: input_ptr, input_len, output_ptr (out), output_len (out)
/// Returns: 0 on success, -1 on parse error, -2 on serialize error
type OpFn = unsafe extern "C" fn(*const u8, usize, *mut *mut u8, *mut usize) -> i32;

/// C ABI function signature for freeing output buffers.
type FreeFn = unsafe extern "C" fn(*mut u8, usize);

/// Global plugin registry — caches loaded libraries.
static PLUGIN_REGISTRY: OnceLock<Mutex<HashMap<PathBuf, Library>>> = OnceLock::new();

fn get_registry() -> &'static Mutex<HashMap<PathBuf, Library>> {
    PLUGIN_REGISTRY.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Build cache — maps raw spec paths to resolved .so paths.
/// Prevents re-running cargo build on every op call.
static BUILD_CACHE: OnceLock<Mutex<HashMap<String, PathBuf>>> = OnceLock::new();

fn get_build_cache() -> &'static Mutex<HashMap<String, PathBuf>> {
    BUILD_CACHE.get_or_init(|| Mutex::new(HashMap::new()))
}

// =============================================================================
// Auto-build: resolve crate paths to shared library paths
// =============================================================================

/// Check if a path is already a shared library.
fn is_shared_lib(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|e| e.to_str()),
        Some("so") | Some("dylib") | Some("dll")
    )
}

/// Walk up from a path to find the nearest Cargo.toml.
fn find_cargo_toml(start: &Path) -> Option<PathBuf> {
    let mut dir = if start.is_file() {
        start.parent()?.to_path_buf()
    } else {
        start.to_path_buf()
    };
    loop {
        let candidate = dir.join("Cargo.toml");
        if candidate.is_file() {
            return Some(candidate);
        }
        if !dir.pop() {
            return None;
        }
    }
}

/// Parse the crate name from Cargo.toml (simple line scanning).
fn parse_crate_name(cargo_toml: &Path) -> Result<String, String> {
    let content = std::fs::read_to_string(cargo_toml)
        .map_err(|e| format!("Failed to read {}: {}", cargo_toml.display(), e))?;
    let mut in_package = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == "[package]" {
            in_package = true;
            continue;
        }
        if trimmed.starts_with('[') {
            in_package = false;
            continue;
        }
        if in_package && trimmed.starts_with("name") {
            if let Some(val) = trimmed.split('=').nth(1) {
                let name = val.trim().trim_matches('"').trim_matches('\'');
                return Ok(name.to_string());
            }
        }
    }
    Err(format!(
        "Could not find crate name in {}",
        cargo_toml.display()
    ))
}

/// Run `cargo build --release` in the crate root directory.
fn build_crate(crate_root: &Path) -> Result<(), String> {
    let output = std::process::Command::new("cargo")
        .args(["build", "--release"])
        .current_dir(crate_root)
        .output()
        .map_err(|e| format!("Failed to run cargo build in {}: {}", crate_root.display(), e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!(
            "cargo build --release failed in {}:\n{}",
            crate_root.display(),
            stderr
        ));
    }
    Ok(())
}

/// Compute the output shared library path for a crate.
fn lib_output_path(crate_root: &Path, crate_name: &str) -> PathBuf {
    // Cargo converts hyphens to underscores in library filenames
    let lib_name = crate_name.replace('-', "_");
    crate_root
        .join("target")
        .join("release")
        .join(format!("{}{}.{}", LIB_PREFIX, lib_name, LIB_EXT))
}

/// Resolve a raw path to a shared library path, auto-building if needed.
///
/// Supports:
/// - `.so`/`.dylib`/`.dll` paths → used directly
/// - `.rs` files → find Cargo.toml, build, resolve to .so
/// - Directories with Cargo.toml → build, resolve to .so
/// - `Cargo.toml` files → use parent as crate root
fn resolve_lib_path(raw_path: &str) -> Result<PathBuf, String> {
    // Check build cache first
    {
        let cache = get_build_cache()
            .lock()
            .map_err(|e| format!("Build cache lock poisoned: {}", e))?;
        if let Some(cached) = cache.get(raw_path) {
            return Ok(cached.clone());
        }
    }

    let path = Path::new(raw_path);
    let abs_path = if path.is_relative() {
        std::env::current_dir()
            .map_err(|e| format!("Failed to get cwd: {}", e))?
            .join(path)
    } else {
        path.to_path_buf()
    };

    let resolved = if is_shared_lib(&abs_path) {
        // Already a .so/.dylib/.dll — use directly
        abs_path
    } else {
        // Find Cargo.toml and auto-build
        let cargo_toml = if abs_path.file_name().map(|f| f == "Cargo.toml").unwrap_or(false) {
            abs_path.clone()
        } else {
            find_cargo_toml(&abs_path).ok_or_else(|| {
                format!(
                    "No Cargo.toml found for '{}'. Expected a .so/.dylib, .rs file, \
                     crate directory, or Cargo.toml path.",
                    raw_path
                )
            })?
        };

        let crate_root = cargo_toml.parent().ok_or_else(|| {
            format!("Invalid Cargo.toml path: {}", cargo_toml.display())
        })?;
        let crate_name = parse_crate_name(&cargo_toml)?;

        // Check if the .so already exists (skip build if so)
        let lib_path = lib_output_path(crate_root, &crate_name);
        if !lib_path.exists() {
            build_crate(crate_root)?;
        }

        if !lib_path.exists() {
            return Err(format!(
                "Build succeeded but library not found at {}. \
                 Ensure the crate has `crate-type = [\"cdylib\"]` in Cargo.toml.",
                lib_path.display()
            ));
        }

        lib_path
    };

    // Cache the resolved path
    {
        let mut cache = get_build_cache()
            .lock()
            .map_err(|e| format!("Build cache lock poisoned: {}", e))?;
        cache.insert(raw_path.to_string(), resolved.clone());
    }

    Ok(resolved)
}

/// Parse a rust op specifier into (library_path, function_name).
///
/// Format: `"path/to/lib.so::func_name"`
pub(crate) fn parse_plugin_spec(spec: &str) -> Option<(&str, &str)> {
    let idx = spec.rfind("::")?;
    let lib_path = &spec[..idx];
    let func_name = &spec[idx + 2..];
    if lib_path.is_empty() || func_name.is_empty() {
        return None;
    }
    Some((lib_path, func_name))
}

/// Load a plugin library and call a function by name.
///
/// 1. Resolves the path (auto-builds from crate if needed)
/// 2. Loads the library (cached after first load)
/// 3. Looks up `rush_op_<func_name>` symbol → extracts raw fn pointers
/// 4. **Drops the registry lock** before calling the op
/// 5. Calls the op with JSON-serialized inputs (lock-free, truly parallel)
/// 6. Frees the output buffer via `rush_ops_free`
/// 7. Returns deserialized JSON output
///
/// This function does NOT require the GIL — it operates entirely in Rust.
/// The registry Mutex is held only during library lookup, NOT during op execution,
/// so concurrent plugin calls run in true parallel.
pub(crate) fn load_and_call(
    lib_path: &str,
    func_name: &str,
    input_json: &[u8],
) -> Result<serde_json::Value, String> {
    // Resolve path: auto-build from crate if not a .so/.dylib
    let abs_path = resolve_lib_path(lib_path)?;

    // Extract raw function pointers under the lock, then drop it.
    // Safe because: libraries are only inserted (never removed) from the cache,
    // so the loaded symbols remain valid for the process lifetime.
    let (op_fn_ptr, free_fn_ptr) = {
        let registry = get_registry();
        let mut libs = registry.lock().map_err(|e| format!("Lock poisoned: {}", e))?;

        // Load library if not cached
        if !libs.contains_key(&abs_path) {
            let lib = unsafe {
                Library::new(&abs_path)
                    .map_err(|e| format!("Failed to load plugin '{}': {}", abs_path.display(), e))?
            };
            libs.insert(abs_path.clone(), lib);
        }

        let lib = libs.get(&abs_path).unwrap();

        // Look up symbols and extract raw pointers (Copy, no borrow on Library)
        let symbol_name = format!("rush_op_{}", func_name);
        let op_fn: Symbol<OpFn> = unsafe {
            lib.get(symbol_name.as_bytes())
                .map_err(|e| format!("Symbol '{}' not found in '{}': {}", symbol_name, lib_path, e))?
        };
        let free_fn: Symbol<FreeFn> = unsafe {
            lib.get(b"rush_ops_free")
                .map_err(|e| format!("Symbol 'rush_ops_free' not found in '{}': {}", lib_path, e))?
        };

        // Dereference Symbol to get raw fn pointers (these are Copy, no lifetime tie)
        let op_raw: OpFn = *op_fn;
        let free_raw: FreeFn = *free_fn;

        (op_raw, free_raw)
        // MutexGuard dropped here — lock released before op execution
    };

    // ── Op execution — lock-free, truly parallel ──
    let mut output_ptr: *mut u8 = std::ptr::null_mut();
    let mut output_len: usize = 0;

    let rc = unsafe { op_fn_ptr(input_json.as_ptr(), input_json.len(), &mut output_ptr, &mut output_len) };

    if rc != 0 {
        return Err(format!(
            "Plugin op '{}::{}' returned error code {}",
            lib_path, func_name, rc
        ));
    }

    if output_ptr.is_null() || output_len == 0 {
        return Err(format!(
            "Plugin op '{}::{}' returned null output",
            lib_path, func_name
        ));
    }

    // Copy output and free the plugin's buffer
    let output_bytes = unsafe { std::slice::from_raw_parts(output_ptr, output_len) }.to_vec();
    unsafe { free_fn_ptr(output_ptr, output_len) };

    // Deserialize output JSON
    serde_json::from_slice(&output_bytes)
        .map_err(|e| format!("Failed to deserialize output from '{}::{}': {}", lib_path, func_name, e))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_plugin_spec() {
        assert_eq!(
            parse_plugin_spec("./lib.so::double"),
            Some(("./lib.so", "double"))
        );
        assert_eq!(
            parse_plugin_spec("/abs/path/lib.so::func"),
            Some(("/abs/path/lib.so", "func"))
        );
        assert_eq!(parse_plugin_spec("no_separator"), None);
        assert_eq!(parse_plugin_spec("::func"), None);
        assert_eq!(parse_plugin_spec("lib.so::"), None);
    }

    #[test]
    fn test_is_shared_lib() {
        assert!(is_shared_lib(Path::new("lib.so")));
        assert!(is_shared_lib(Path::new("lib.dylib")));
        assert!(is_shared_lib(Path::new("lib.dll")));
        assert!(!is_shared_lib(Path::new("lib.rs")));
        assert!(!is_shared_lib(Path::new("my_crate")));
        assert!(!is_shared_lib(Path::new("Cargo.toml")));
    }

    #[test]
    fn test_parse_crate_name() {
        let dir = std::env::temp_dir().join("test_parse_crate_name");
        std::fs::create_dir_all(&dir).unwrap();
        let toml = dir.join("Cargo.toml");
        std::fs::write(
            &toml,
            "[package]\nname = \"my-crate\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
        assert_eq!(parse_crate_name(&toml).unwrap(), "my-crate");
        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn test_lib_output_path() {
        let root = Path::new("/tmp/my-crate");
        let result = lib_output_path(root, "my-crate");
        let expected = PathBuf::from(format!(
            "/tmp/my-crate/target/release/{}my_crate.{}",
            LIB_PREFIX, LIB_EXT
        ));
        assert_eq!(result, expected);
    }
}
