[package]
name = "my-hush-ops"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "my-hush-ops"
path = "src/main.rs"

[dependencies]
hush-icore = { git = "https://github.com/batman1m2001-cyber/Hush-ai", branch = "main" }
hush-serve = { git = "https://github.com/batman1m2001-cyber/Hush-ai", branch = "main" }
hush-providers = { git = "https://github.com/batman1m2001-cyber/Hush-ai", branch = "main" }
hush-macros = { git = "https://github.com/batman1m2001-cyber/Hush-ai", branch = "main" }
serde_json = "1"
inventory = "0.3"
